Added coverage reporting, lint passing, enabled Bionic
alchemy-charmers/layer-haproxy pull request #13
Opened 2019-11-25 23:47 UTC by devec0

Enabled Bionic, and updated formatting to make sure lint passed whilst I was there.
Also added the new coverage reporting stuff.

2019-11-27 16:16 UTC, chris-sanders requested changes
See comments in-line

2019-11-27 16:16 UTC, chris-sanders commented on tox.ini
> +commands = flake8 --max-complexity=40 --format=html --htmldir=report/lint/ --tee
This folder doesn't exist you'll need to put an empty file to pre-create it in the repo.

FileNotFoundError: [Errno 2] No such file or directory: 'report/lint/'
ERROR: InvocationError for command '/home/chris/src/juju/charms/layers/layer-haproxy/.tox/lint/bin/flake8 --max-complexity=40 --format=html --htmldir=report/lint/ --tee' (exited with code 1)

2019-11-27 16:16 UTC, chris-sanders commented on tox.ini
> +commands = flake8 --max-complexity=40 --format junit-xml --output-file=report/lint/junit.xml
I like the report outputs, but can you still generate the terminal output? 
When building a charm simply getting "has issues" on the terminal makes it much harder to review/fix. It's great when part of a pipeline to have html but I really don't want to give up the current terminal output. Push comes to shove, I'd rather have the terminal than the HTML until/unless there's a CI pipeline showing results of MRs.

2019-11-27 16:16 UTC, chris-sanders commented on tox.ini
> +	    --html=report/unit/tests/index.html \
This fails to run, I presume you want pytest-html added to tests/unit/requirements.txt to install it in the venv?

2019-11-27 16:16 UTC, chris-sanders commented on tests/unit/test_libhaproxy.py
> +def test_process_configs(ph, monkeypatch, config):
While I *think* this big diff is just Black unit testing is failing for me on at least 3 different tests. I don't know that it's introduced with this branch but have you looked at why these are failing? This charm didn't use to have failing tests, I might see if I can look into that later because I'm concerned this isn't about this patch but possibly something else that's actually a critical failing in the config writer.

2019-11-27 20:30 UTC, devec0 commented on tox.ini
> +commands = flake8 --max-complexity=40 --format=html --htmldir=report/lint/ --tee
Fixed, added a stub file, simply forgot.

2019-11-27 20:32 UTC, devec0 commented on tox.ini
> +commands = flake8 --max-complexity=40 --format junit-xml --output-file=report/lint/junit.xml
So, I've dug into this a fair bit, and the best I could get to was the current summary output, which shows the file and number of errors. At first, I didn't like that, but I've actually grown to find it much more convenient than paging around my terminal to look at the issues - the file listing gives me an actionable list of files I need to pop open in my editor, and my editor shows me all the issues in place - I've found that to be a very comfortable workflow.

I'm happy to look further at this, but I couldn't find a way other than to run the lint twice to get both the HTML and traditional terminal-based report at the same time.

2019-11-27 20:32 UTC, devec0 commented on tox.ini
> +	    --html=report/unit/tests/index.html \
Fixed, just forgot to backport the requirements.txt

2019-11-27 20:33 UTC, devec0 commented on tests/unit/test_libhaproxy.py
> +def test_process_configs(ph, monkeypatch, config):
Nope, this was totally broken. I must have run the tests before addressing the lint findings, and a stray regex replaced a lower case 'config' with the 'haproxy_config' module in the HTTP backend check function. I've fixed it now and tests are passing again.

2019-11-27 21:09 UTC, chris-sanders commented on tox.ini
> +commands = flake8 --max-complexity=40 --format junit-xml --output-file=report/lint/junit.xml
That sounds super reasonable, you'll have to show me that some day. Let's leave this as you have here sounds like you've give in due thought we've got more important things to work on!

2019-11-27 21:13 UTC, chris-sanders commented on tox.ini
> +	    --html=report/unit/tests/index.html \
Oops same thing to tests/functional/requirements.txt

2019-11-27 21:15 UTC, chris-sanders requested changes
You'll have to leave bionic as 'canary' in functional testing until this branch lands and is on the charm store. It fails to deploy (b/c the charmstore doesn't allow bionic) a later merge can promote bionic from canary in testing once the charm store supports it.

2019-12-11 18:49 UTC, chris-sanders commented
I merged master, and fixed the functional testing so I'll merge this.

2019-12-11 18:50 UTC, merged